spring:
  application:
    name: department-service
  config:
    import : "optional:configserver:http://localhost:8088"

server:
  port: 8081
#
#spring:
#  application:
#    name: department-service
#  cloud:
#    config:
#      import: "optional:config-server:http://localhost:8088"